package testcases;

import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
public class App
{
	public static void main( String[] args )
	{
		// Put recipient’s address
		String to = "maddinenilatha522@gmail.com";
		// Put sender’s address
		String from = "singaraomaddineni@gmail.com";
		final String username = "singaraomaddineni@gmail.com";//username generated by Pepipost
		final String password = "daqepcgsuaplbuwg";//password generated by Pepipost
		// Paste host address from the SMTP relay tab in Integrations from your Pepipost App
		String host = "smtp.gmail.com";
		Properties props = new Properties();
		props.put("mail.smtp.auth", "true");
		//props.put("mail.smtp.starttls.enable", "true");
		props.put("mail.smtp.host", host);
		props.put("mail.smtp.port", "587");
		// Get the Session object.
		Session session = Session.getInstance(props,
				new javax.mail.Authenticator() {
			protected PasswordAuthentication getPasswordAuthentication() {
				return new PasswordAuthentication(username, password);
			}
		});
		session.setDebug(true);
		try {
			// Create a default MimeMessage object.
			Message message = new MimeMessage(session);
			// Set From: header field
			message.setFrom(new InternetAddress(from));
			// Set To: header field
			message.setRecipients(Message.RecipientType.TO,
					InternetAddress.parse(to));
			// Set Subject: header field
			message.setSubject("My first message with JavaMail");
			// Put the content of your message
			message.setText("Hi there, this is my first message sent with JavaMail");
			// Send message
			System.out.println("Sending msg");
			Transport.send(message);
			System.out.println("Sent message successfully....");
		} catch (MessagingException e) {
			throw new RuntimeException(e);
		}
	}
}